export interface Product {
  id: number;
  name: string;
  slug: string;
  price: number;
  regularPrice?: number;
  sizes: string[];
  image: string;
  categories: string[];
  featured?: boolean;
  soldOut?: boolean;
  batchNumber?: string;
  description: string;
  researchInfo?: string;
  purity?: string;
  formula?: string;
  molecularWeight?: string;
  format?: string;
  storage?: string;
  researchBullets?: string[];
  peptideType?: string;
  aminoAcidLength?: string;
  peptideOrigin?: string;
}

const CDN = "https://yourhealthsupply.ca/cdn/shop/files";

export const allProducts: Product[] = [
  {
    id: 1,
    name: "GLP3",
    slug: "vitalis-rta",
    price: 69.99,
    sizes: ["5mg", "10mg", "20mg"],
    image: `${CDN}/GLP3_Reta__5mg_10mg.png?v=1786585054`,
    categories: ["metabolic", "all-peptides"],
    featured: true,
    batchNumber: "BW-RETA-10-040626",
    description: "GLP-3 is a triple hormone receptor agonist targeting GIP, GLP-1, and glucagon receptors. Supplied as a lyophilized research material for laboratory investigation of multi-receptor metabolic signalling pathways.",
    researchInfo: "(LY3437943) is an investigational triple agonist targeting GIP, GLP-1, and glucagon receptors, studied in preclinical models for its role in multi-pathway receptor signalling and metabolic pathway research.",
    purity: ">99.43%",
    formula: "C221H342N46O68",
    molecularWeight: "4731.33",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 2,
    name: "BPC-157",
    slug: "bpc-157-5mg",
    price: 49.99,
    regularPrice: 59.99,
    sizes: ["5mg", "10mg"],
    image: `${CDN}/BPC_157_5mg_10mg.png?v=1786584884`,
    categories: ["tissue-repair", "all-peptides"],
    featured: true,
    batchNumber: "#BW-BPC1-10-040626",
    description: "BPC-157 (Body Protective Compound-157) is a synthetic pentadecapeptide supplied as a high-purity lyophilized compound intended exclusively for laboratory research use by qualified professionals. Manufactured under controlled conditions to ensure consistency, stability, and analytical reliability.",
    researchInfo: "BPC-157 has been studied in in vitro and animal models for its role in cell signaling modulation and tissue-level adaptive responses. Research applications focus on mechanistic exploration and biological pathway analysis, not therapeutic use.",
    researchBullets: [
      "Tissue repair and regenerative signaling pathways",
      "Angiogenesis and vascular integrity mechanisms",
      "Modulation of inflammatory signaling cascades",
      "Gastrointestinal mucosal protection models",
      "Tendon, ligament, and musculoskeletal injury models",
      "Cellular migration and extracellular matrix interaction",
    ],
    peptideType: "Synthetic pentadecapeptide",
    aminoAcidLength: "15 amino acids",
    peptideOrigin: "Fragment derived from a gastric protective protein sequence (synthetic analogue)",
    purity: "98.37% (HPLC)",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 3,
    name: "TB-500",
    slug: "tb-500-5mg",
    price: 99.99,
    sizes: ["5mg", "10mg"],
    image: `${CDN}/TB-500_5mg_10mg.png?v=1786584816`,
    categories: ["tissue-repair", "all-peptides"],
    featured: true,
    description: "TB-500 (Thymosin Beta-4) is a naturally occurring peptide supplied as a lyophilized research material for laboratory investigation of cell migration, vascular signalling, and structural repair pathway research.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 4,
    name: "WOLVERINE BLEND (BPC-157+TB500)",
    slug: "wolverine",
    price: 89.99,
    regularPrice: 99.99,
    sizes: ["10mg", "20mg"],
    image: `${CDN}/WOLVERINE_BLEND__BPC-157_TB500__10mg_30mg_8db53782-95c1-4b3d-aebb-eb89561d4484.png?v=1786586091`,
    categories: ["tissue-repair", "blends", "all-peptides"],
    featured: true,
    description: "The Wolverine Blend combines BPC-157 and TB-500 into a single vial for enhanced tissue repair and recovery. Both peptides work synergistically to accelerate healing and reduce recovery time.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 5,
    name: "CJC-1295 & Ipamorelin Blend",
    slug: "cjc-1295-ipamorelin-10mg",
    price: 89.99,
    sizes: ["10mg"],
    image: `${CDN}/CJC-1295_Ipamorelin_6dd75a81-856c-4bc9-be57-7b1dce98da4a.png?v=1786590175`,
    categories: ["metabolic", "blends", "all-peptides"],
    featured: true,
    description: "The CJC-1295 & Ipamorelin blend combines two powerful growth hormone secretagogues for synergistic effects on growth hormone release, body composition, and recovery.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 6,
    name: "GHK-Cu (Copper)",
    slug: "ghk-cu-100mg",
    price: 49.99,
    sizes: ["50mg", "100mg"],
    image: `${CDN}/GHK-Cu_Copper.png?v=1786621553`,
    categories: ["cellular-anti-aging", "all-peptides"],
    featured: true,
    description: "GHK-Cu (Copper Peptide) is a naturally occurring copper complex of the tripeptide glycyl-L-histidyl-L-lysine. It promotes wound healing, attracts immune cells, and has antioxidant and anti-inflammatory effects.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 7,
    name: "GLOW70 Blend",
    slug: "glow-70",
    price: 149.99,
    regularPrice: 159.99,
    sizes: ["70mg"],
    image: `${CDN}/GLOW70Blend_70mg_0057a8b6-db53-4944-bfe9-f8a96319449d.png?v=1786620079`,
    categories: ["cellular-anti-aging", "blends", "all-peptides"],
    description: "The GLOW70 Blend is a comprehensive anti-aging formula designed for cellular rejuvenation and skin health. This powerful combination targets multiple aging pathways simultaneously.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 8,
    name: "KLOW80 Blend",
    slug: "klow-80",
    price: 189.99,
    regularPrice: 199.99,
    sizes: ["80mg"],
    image: `${CDN}/KLOW80Blend_80mg_b74f13ff-3b20-4002-aeed-69a32285f577.png?v=1786619944`,
    categories: ["metabolic", "blends", "all-peptides"],
    description: "The KLOW80 Blend is an advanced metabolic support formula combining multiple peptides for comprehensive weight management and metabolic enhancement.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 9,
    name: "5-Amino-1MQ (coming soon)",
    slug: "5-amino-1mq",
    price: 159.99,
    sizes: ["50mg"],
    image: `${CDN}/5-Amino-1MQ-50mg.jpg?v=1786622196`,
    categories: ["metabolic", "all-peptides"],
    soldOut: true,
    description: "5-Amino-1MQ is a small molecule inhibitor of NNMT (nicotinamide N-methyltransferase), an enzyme that is highly expressed in adipose tissue and associated with obesity and metabolic disease.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 10,
    name: "AOD9604",
    slug: "aod9604",
    price: 99.99,
    sizes: ["5mg", "10mg"],
    image: `${CDN}/AOD9604_5mg_10mg.png?v=1786589317`,
    categories: ["metabolic", "all-peptides"],
    description: "AOD9604 is a modified form of amino acids 176-191 of the GH polypeptide. It mimics the way natural growth hormone regulates fat metabolism without the negative effects on blood sugar or cell proliferation.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 11,
    name: "CJC-1295 no DAC",
    slug: "cjc-1295-without-dac",
    price: 39.99,
    regularPrice: 59.99,
    sizes: ["5mg"],
    image: `${CDN}/CJC_NODAC_5mg_10mg.png?v=1786589115`,
    categories: ["metabolic", "all-peptides"],
    description: "CJC-1295 without DAC (Drug Affinity Complex) is a synthetic analogue of growth hormone releasing hormone (GHRH). It stimulates growth hormone secretion and increases levels of insulin-like growth factor 1 (IGF-1).",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 12,
    name: "Ipamorelin",
    slug: "ipamorelin",
    price: 49.99,
    regularPrice: 89.99,
    sizes: ["10mg"],
    image: `${CDN}/Ipamorelin_10mg.png?v=1786588351`,
    categories: ["metabolic", "all-peptides"],
    description: "Ipamorelin is a selective growth hormone secretagogue that stimulates the pituitary gland to produce more growth hormone. It is known for its selectivity, causing minimal side effects compared to other GH secretagogues.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 13,
    name: "DSIP",
    slug: "dsip",
    price: 69.99,
    sizes: ["5mg"],
    image: `${CDN}/DSIP_5mg_10mg.png?v=1786585685`,
    categories: ["neuro", "all-peptides"],
    description: "DSIP (Delta Sleep-Inducing Peptide) is a neuropeptide that has been researched for its effects on sleep regulation, stress response, and various neuroendocrine functions.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 14,
    name: "SS-31 (Elamipretide)",
    slug: "elamipretide-ss31-40mg",
    price: 169.99,
    regularPrice: 189.99,
    sizes: ["40mg"],
    image: `${CDN}/Elamipretide_SS-31.png?v=1786619592`,
    categories: ["cellular-anti-aging", "all-peptides"],
    description: "SS-31 (Elamipretide) is a cell-permeable tetrapeptide that targets the inner mitochondrial membrane. It has been researched for its potential in treating mitochondrial dysfunction and age-related conditions.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 15,
    name: "Epitalon",
    slug: "epitalon-10mg",
    price: 84.99,
    sizes: ["10mg"],
    image: `${CDN}/Epitalon_5mg_10mg.png?v=1786620686`,
    categories: ["cellular-anti-aging", "all-peptides"],
    description: "Epitalon is a synthetic tetrapeptide derived from the natural peptide Epithalamin, extracted from the pineal gland. It is researched for its potential to activate telomerase and extend telomere length.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 16,
    name: "GLP2",
    slug: "vitalis-trz",
    price: 69.99,
    sizes: ["5mg", "10mg", "20mg"],
    image: `${CDN}/GLP25_5mg_10mg_30mg.png?v=1786586786`,
    categories: ["metabolic", "all-peptides"],
    description: "GLP-2 is a dual-receptor agonist research material supplied for laboratory investigation of multi-receptor metabolic and intestinal signalling pathways.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 17,
    name: "Glutathione",
    slug: "glutathione",
    price: 99.99,
    sizes: ["1500mg"],
    image: `${CDN}/Glutathione_fc8eb286-bfb9-4756-aebe-541b95887dcd.png?v=1786622982`,
    categories: ["cellular-anti-aging", "all-peptides"],
    description: "Glutathione is the body's master antioxidant, a tripeptide composed of glutamine, cysteine, and glycine. It plays a crucial role in immune function, toxin elimination, and protection against oxidative stress.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 18,
    name: "IGF-1",
    slug: "vtl-igf0110x",
    price: 189.99,
    sizes: ["1mg"],
    image: `${CDN}/IGF-1_1mg.png?v=1786588937`,
    categories: ["metabolic", "all-peptides"],
    description: "IGF-1 (Insulin-like Growth Factor 1) is a hormone similar in molecular structure to insulin. It plays an important role in childhood growth and continues to have anabolic effects in adults.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 19,
    name: "Kisspeptin",
    slug: "kisspeptin",
    price: 79.99,
    sizes: ["10mg"],
    image: `${CDN}/Kisspeptin_10mg.png?v=1786622325`,
    categories: ["neuro", "all-peptides"],
    description: "Kisspeptin is a neuropeptide that plays a critical role in puberty, reproduction, and metabolism. It acts on hypothalamic neurons to stimulate the release of gonadotropin-releasing hormone (GnRH).",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 20,
    name: "KPV",
    slug: "kpv-1",
    price: 99.99,
    sizes: ["10mg"],
    image: `${CDN}/KPV_10mg.png?v=1786587300`,
    categories: ["tissue-repair", "all-peptides"],
    description: "KPV is a tripeptide fragment of alpha-MSH (alpha-melanocyte stimulating hormone) with potent anti-inflammatory properties. It has been researched for inflammatory bowel disease and skin inflammation.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 21,
    name: "Melanotan II",
    slug: "melanotan-ii",
    price: 69.99,
    sizes: ["10mg"],
    image: `${CDN}/Melanotan_II.png?v=1786587894`,
    categories: ["cellular-anti-aging", "all-peptides"],
    description: "Melanotan II is a synthetic analogue of the peptide hormone alpha-melanocyte-stimulating hormone (α-MSH). It has been researched for its effects on skin pigmentation and related processes.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 22,
    name: "MOTS-C",
    slug: "mots-c-10mg",
    price: 59.99,
    sizes: ["10mg", "20mg", "40mg"],
    image: `${CDN}/MOTS-C_10mg_40mg.png?v=1786619501`,
    categories: ["metabolic", "all-peptides"],
    featured: true,
    description: "MOTS-C is a peptide encoded by the mitochondrial genome that regulates metabolic homeostasis and insulin sensitivity. It has been studied for its role in exercise physiology and metabolic health.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 23,
    name: "NAD+",
    slug: "nad",
    price: 99.99,
    sizes: ["500mg", "1000mg"],
    image: `${CDN}/NAD_500mg_1000mg.png?v=1786619223`,
    categories: ["cellular-anti-aging", "metabolic", "all-peptides"],
    description: "NAD+ (Nicotinamide Adenine Dinucleotide) is a coenzyme found in all living cells. It plays a crucial role in energy metabolism, DNA repair, and cellular signaling. Declining NAD+ levels with age are linked to age-related conditions.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
  {
    id: 24,
    name: "PNC-27 (coming soon)",
    slug: "pnc-27",
    price: 189.99,
    sizes: ["5mg"],
    image: `${CDN}/PNC-27.png?v=1786622573`,
    categories: ["cellular-anti-aging", "all-peptides"],
    soldOut: true,
    description: "PNC-27 is a peptide derived from the p53 tumor suppressor protein. It has been researched for its selective ability to target cancer cells while leaving normal cells unaffected.",
    purity: ">99%",
    format: "Lyophilized powder",
    storage: "2–8 °C, protected from light",
  },
];

export const supplies: Product[] = [
  {
    id: 101,
    name: "Bacteriostatic Water (BAC Water)",
    slug: "bac-water",
    price: 19.99,
    sizes: ["20ml"],
    image: `${CDN}/BAC_Water_20ml.png?v=1786623190`,
    categories: ["supplies"],
    description: "Bacteriostatic Water is sterile water containing 0.9% benzyl alcohol, supplied for laboratory research use.",
  },
  {
    id: 102,
    name: "10 Pack 1ml Syringe's",
    slug: "10-pack-syringes",
    price: 14.99,
    sizes: ["1ml"],
    image: `${CDN}/be2afa83-d2a1-426d-ad65-3c6ba76e5ade.webp?v=1786631441`,
    categories: ["supplies"],
    description: "Pack of 10 insulin syringes with 1ml capacity and 100IU markings. For accurate laboratory measurement of research compounds.",
  },
  {
    id: 103,
    name: "Alcohol Prep Pads (200)",
    slug: "alcohol-prep-pads-200",
    price: 9.99,
    sizes: ["200 pack"],
    image: `${CDN}/030982d7-42c9-44db-8d0f-ab8eb5070d89.png?v=1786630831`,
    categories: ["supplies"],
    description: "200-count alcohol prep pads for sterilizing vial tops and maintaining proper sterile technique during laboratory handling of research compounds.",
  },
  {
    id: 104,
    name: "10 Pack 0.5ml Syringe's",
    slug: "10-pack-syringes-copy",
    price: 14.99,
    sizes: ["0.5ml"],
    image: `${CDN}/c5192332-5569-4f3f-87f1-67f1e895b626.png?v=1786631461`,
    categories: ["supplies"],
    description: "Pack of 10 insulin syringes with 0.5ml capacity and 50IU markings. For accurate laboratory measurement of research compounds.",
  },
];

export const collections = {
  "all-peptides": {
    name: "Full Peptide Collection",
    slug: "all-peptides",
    description: "Complete range of research-grade peptides",
    products: allProducts,
  },
  "healthcare-example-products": {
    name: "Full Peptide Collection",
    slug: "all-peptides",
    description: "Complete range of research-grade peptides",
    products: allProducts,
  },
  blends: {
    name: "Blended Compounds",
    slug: "blends",
    description: "Pre-blended peptide combinations for enhanced research protocols",
    products: allProducts.filter((p) => p.categories.includes("blends")),
  },
  supplies: {
    name: "Research Supplies",
    slug: "supplies",
    description: "Laboratory supplies for handling and storing research materials",
    products: supplies,
  },
  "cosmetic-anti-aging": {
    name: "Cellular & Anti-Aging",
    slug: "cosmetic-anti-aging",
    description: "Peptides researched for cellular health and anti-aging applications",
    products: allProducts.filter((p) => p.categories.includes("cellular-anti-aging")),
  },
  "recovery-regeneration": {
    name: "Tissue Repair",
    slug: "recovery-regeneration",
    description: "Peptides studied for tissue repair and regeneration",
    products: allProducts.filter((p) => p.categories.includes("tissue-repair")),
  },
  neurological: {
    name: "Neuro Health",
    slug: "neurological",
    description: "Peptides researched for neurological and cognitive applications",
    products: allProducts.filter((p) => p.categories.includes("neuro")),
  },
  "weight-loss-metabolism": {
    name: "Metabolic Health",
    slug: "weight-loss-metabolism",
    description: "Peptides studied for metabolic health and weight management",
    products: allProducts.filter((p) => p.categories.includes("metabolic")),
  },
};

export const allProductsWithSupplies = [...allProducts, ...supplies];

export function getProductBySlug(slug: string): Product | undefined {
  return allProductsWithSupplies.find((p) => p.slug === slug);
}

export const popularProducts = allProducts.filter((p) => p.featured);

export const categoryCards = [
  {
    name: "Cellular & Anti-Aging",
    slug: "cosmetic-anti-aging",
    image: `https://yourhealthsupply.ca/cdn/shop/collections/Cosmetic.png?v=1786625196`,
  },
  {
    name: "Tissue Repair",
    slug: "recovery-regeneration",
    image: `https://yourhealthsupply.ca/cdn/shop/collections/Recovery.png?v=1786625144`,
  },
  {
    name: "Neuro Health",
    slug: "neurological",
    image: `https://yourhealthsupply.ca/cdn/shop/collections/Neuro.png?v=1786625100`,
  },
  {
    name: "Metabolic Health",
    slug: "weight-loss-metabolism",
    image: `https://yourhealthsupply.ca/cdn/shop/collections/Weight_Loss_Metabolism_1ffe094b-c51d-49e6-963c-dab8a3ff5119.png?v=1786625283`,
  },
];

export const collectionCards = [
  {
    name: "Blended Compounds",
    slug: "blends",
    image: `https://yourhealthsupply.ca/cdn/shop/collections/blend.png?v=1786625006`,
  },
  {
    name: "Full Peptide Collection",
    slug: "all-peptides",
    image: `https://yourhealthsupply.ca/cdn/shop/collections/4bd18ab0-08c7-45ec-af9c-b61ef0faa63d.png?v=1786624925`,
  },
  {
    name: "Popular",
    slug: "popular",
    image: `https://yourhealthsupply.ca/cdn/shop/collections/light_629ccdc4-32f2-4d75-bce4-7fce1be6d9e0.png?v=1786625401`,
  },
  {
    name: "Research Supplies",
    slug: "supplies",
    image: `https://yourhealthsupply.ca/cdn/shop/collections/light_cba1c998-1b31-4730-bd86-29be0fd67866.png?v=1786625073`,
  },
];
